apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-b
  template:
    metadata:
      labels:
        app: servicio-b
    spec:
      containers:
      - name: servicio-b
        image: servicio-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
