apiVersion: v1
kind: Service
metadata:
  name: servicio-a
spec:
  selector:
    app: servicio-a
  ports:
  - protocol: TCP
    port: 50051       # Puerto dentro del clúster
    targetPort: 50051 # Puerto dentro del contenedor
