# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import saludo_personalizado_pb2 as saludo__personalizado__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in saludo_personalizado_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SaludadorPersonalizadoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaludoCompleto = channel.unary_unary(
                '/saludo_personalizado.SaludadorPersonalizado/SaludoCompleto',
                request_serializer=saludo__personalizado__pb2.SaludoCompletoRequest.SerializeToString,
                response_deserializer=saludo__personalizado__pb2.SaludoCompletoReply.FromString,
                _registered_method=True)


class SaludadorPersonalizadoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaludoCompleto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaludadorPersonalizadoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaludoCompleto': grpc.unary_unary_rpc_method_handler(
                    servicer.SaludoCompleto,
                    request_deserializer=saludo__personalizado__pb2.SaludoCompletoRequest.FromString,
                    response_serializer=saludo__personalizado__pb2.SaludoCompletoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saludo_personalizado.SaludadorPersonalizado', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saludo_personalizado.SaludadorPersonalizado', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SaludadorPersonalizado(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaludoCompleto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saludo_personalizado.SaludadorPersonalizado/SaludoCompleto',
            saludo__personalizado__pb2.SaludoCompletoRequest.SerializeToString,
            saludo__personalizado__pb2.SaludoCompletoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
